version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "TodoGatewayTest"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-lmjukhdcb4xb"
s3_prefix = "TodoGatewayTest"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
