name: Linux

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ['5.1']
    container:
      image: swift:${{ matrix.tag }}
      volumes:
      - $GITHUB_WORKSPACE:/src
      options: --workdir /src
    steps:
    - uses: actions/checkout@v1
    - name: Fetch Dependencies
      run: apt-get update && apt-get install -y openssl libssl-dev
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test --enable-code-coverage --enable-test-discovery
    - name: Convert coverage
      run: llvm-cov export -format="lcov" .build/debug/DynamoCoderPackageTests.xctest -instr-profile .build/debug/codecov/default.profdata > info.lcov
    - name: Code Coverage
      uses: codecov/codecov-action@v1.0.3
      with:
        token: ${{secrets.CODECOV_TOKEN}}
