name: MacOS

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
    - name: XCode Tests
      run: |
        swift package generate-xcodeproj
        xcodebuild -quiet -parallel-testing-enabled YES -scheme DynamoCoder-Package -enableCodeCoverage YES build test
    - name: Code Coverage
      run:
          bash <(curl -s https://codecov.io/bash) -J DynamoCoder -t ${{secrets.CODECOV_TOKEN}}
